#!/usr/bin/python3
# -*- coding: utf-8 -*-

import numpy as np
import sys, os

def dp():

  start = 1

  d = np.array([[1, 2, 2, 2, 1, 3],
                  [1, 3, 1, 3, 2, 2],
                  [3, 2, 2, 1, 3, 2],
                  [1, 1, 3, 1, 3, 3],
                  [2, 3, 1, 1, 2, 2]])

  g = np.zeros((5, 6))
  g[0,0]=d[0,0]

  number = []
  
  for j in range(1,5):
    for i in range(1,6):
      if i==0 and j==0:
        g[j,i]=d[0,0]
        continue
      g1 = 100
      g2 = 101
      g3 = 102
      """
      if j>0:
        g1 = g[j-1,i] + d[j,i]
      elif i>0:
        g3 = g[j,i-1] + d[j,i]
      elif i>0 and j>0:
        g2 = g[j-1,i-1] + 2*d[j,i]
      """
      if j==0 and i>0:
        g3 = g[j,i-1] + d[j,i]
      if i==0 and j>0:
        g1 = g[j-1,i] + d[j,i]
      if i>0 and j>0:
        g2 = g[j-1,i-1] + 2*d[j,i]


        g[j,i] = min(g1, g2)
        g[j,i] = min(g[j,i], g3)
        print(g[j,i])
        print(i, j)
        if g1 < g3:
          i=5

  print(g[4,5])

def main():

  dp()

if __name__ == "__main__":

  main()
